# Generated by Django 3.2.6 on 2022-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0002_auto_20221227_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
